services:
  web:
    build:
      context: ./user
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./user:/var/www/html:cached
    depends_on:
      - mongo_database
    environment:
      - MONGO_HOST=mongo_database
      - MONGO_PORT=27017
      - MONGO_DB=archiDistriRestaurants
  avis:
    build: 
      context: ./avis
    container_name: avis_service
    ports:
      - "3200:3200" 
    environment:
      - MONGO_HOST=mongo_database
      - MONGO_PORT=27017
      - MONGO_DB=archiDistriRestaurants
    depends_on:
      - mongo_database
  restaurant:
    build: ./restaurant
    container_name: restaurant_service
    ports:
      - "50051:50051" 
    environment:
      - USE_MONGO=true
      - MONGO_URL=mongodb://mongo_database:27017/archiDistriDB
      - USE_DOCKER=true
    depends_on:
      - mongo_database
    restart: unless-stopped


  mongo_database:
    image: mongodb/mongodb-community-server:7.0-ubi8 # Cette version inclut les outils d'import
    container_name: mongo_database
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./data:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_DATABASE=archiDistriRestaurants

volumes:
  mongo_data:
 