services:
  mongo:
    image: mongo:6
    container_name: mongocaca
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=archiDistriRestaurants

volumes:
  mongo_data:
