services:
  web:
    build:
      context: ./user
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./user:/var/www/html:cached
    depends_on:
<<<<<<< HEAD
      - mongo_database
    environment:
      - MONGO_HOST=mongo_database
      - MONGO_PORT=27017
      - MONGO_DB=archiDistriRestaurants

  mongo_database:
    image: mongo:6
    container_name: mongo_database
=======
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=archiDistriRestaurants

  mongo:
    image: mongo:6
    container_name: mongo
>>>>>>> 5e5ec9e03094316b728794fabadef7886e83f63d
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./data:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_DATABASE=archiDistriRestaurants

volumes:
  mongo_data:
